# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 80

# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver

        url: jdbc:mysql://10.138.228.199:33528/hmzy_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowMultiQueries=true
        username: root
        password: abc!@#123
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

pack:
  zipName: haier.zip
  package: com.haier


